apiVersion: ai.sap.com/v1alpha1
kind: ServingTemplate
metadata:
  name: tf-text-clf-serve
  annotations:
    scenarios.ai.sap.com/description: "Tensorlfow text classification"
    scenarios.ai.sap.com/name: "movie-review-clf"
    executables.ai.sap.com/description: "Tensorlfow GPU Serving executable"
    executables.ai.sap.com/name: "serve-exectuable"
  labels:
    scenarios.ai.sap.com/id: "tf-text-clf"
    ai.sap.com/version: "1.0.0"
spec:
  inputs:
    artifacts:
    - name: modelArtifact
  template:
    apiVersion: "serving.kserve.io/v1beta1"
    metadata:
      labels: |
        ai.sap.com/resourcePlan: infer.s
    spec: |
      predictor:
        imagePullSecrets:
          - name: my-secret
        containers:
        - name: kfserving-container
          image: "docker.io/abhinavpanthri/9145e5924f0f3c8523cf3fcd1bcd0010acf3ac6d9387a21d4958c0e65ab975b8"
          ports:
            - containerPort: 9001
              protocol: TCP
          env:
            - name: STORAGE_URI
              value: "{{inputs.artifacts.modelArtifact}}"
